travis:
  secure:
    BINSTAR_TOKEN: eZP6QugW5CZecjSJJd/gPTn+KTK1DkuYTiDqIXN5wcFs9t+XrUk3cETPrryGwkXWKkzjxHVCAibPoAhNFrpS/7ci/uM8EBen+bxm9NxlzOwV9w/cwHN8ChBW0niNam3Pq478av9nQULabhwSx67CtgflJxpS4yX79x9xTuFHJmY+040pqA8rHDDCBbOq9Uqk8jacwnm70JMI979qW5en3b8gwQVXZ/v/B+Z6SdV9Pq2pFGe24L21Zk90+CWoPKEE8p9IjjiKx3IV9hhwX2gOxaFbcUMTWJJziG/DlnsXR632OPhkW120wOV73+SkpBhrsZJ+Y3VBlQEe0er0lkHlI7jdb7pxkcDqptbK8lNCLL1kt6Oc9Lu+ZQsAmKH1Ff+TXd2D3Dw1Hazj0m2Moglq9YjcfopeLXFq7YYXOg/CQIcEqzb5/eUrE/62KurcLw0t7UZCcKmtVfWB/39unQQyZFT15hxVWoWSGTgYPFpgc8GByXaaWQRCyyNVOqaFHWLcOhHd5FqjzenjMCMXdpRQ2nTOgaYfjlSCYiOiEMXWNe0SpfVkafVjLliaHBnvOg1SSdKvgoCMi//743IFZckOpHcS6OwCTfCAKKtt0yA7nNP0Ue6GDSF3Ib6QH6rOXB3oioHp475WfoXRMakDF9ToQSpmGHVwlxO0hxU3cEWffI8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
